### ISSUE TITLE
Range picker

### ISSUE THREAD

**Issue by TrejGun** [tempusdominus/bootstrap-3#1]
please add range picker mode with 2 months on the same popup similar to http://www.daterangepicker.com/#examples

**Comment by pixxet** [comment]
+1

**Comment by koryukov** [comment]
@TrejGun, there is the [Range feature](https://github.com/Eonasdan/bootstrap-datetimepicker/pull/2211) pull request in the *Eonasdan/bootstrap-datetimepicker* repository. Unfortunately, the one it is no longer actively monitor or supported. But I hope the code from the pull request will be useful for you.

**Comment by TrejGun** [comment]
@koryukov thanks
