### ISSUE TITLE
Integrate picker into WordPress

### ISSUE THREAD

**Issue by evanre** [tempusdominus/bootstrap-3#10]
Hi, I'm trying to integrate your datetimepicker plugin into WordPress ContactForm7 plugin. Unfortunately this plugin didn't support data-attributes. I have only classes and id's or any html around inputs. Docs for your plugin says that for minimum setup (No Icon) I can use this code:
```html
<div class="col-sm-6">
    <input type="text" class="form-control" id="datetimepicker5" />
</div>
```
But the real code looks like this:
```html
<div class="col-sm-6">
    <input type="text" class="form-control" id="datetimepicker5" data-toggle="datetimepicker" data-target="#datetimepicker5"/>
</div>
```
And it didn't work without this data-attributes.

Please help. Thank you!

PS I get alpha version because I didn't use Bootstrap.

**Comment by Eonasdan** [comment]
Unfortunately, you'll have to contact Takayuki Miyoshi the author of the contact form 7 about that. Or you can look at https://andidittrich.de/2016/12/contact-form-7-add-custom-data-providers-to-select-elementstags.html or https://wordpress.org/support/topic/adding-data-attributes-to-radio-buttons/
