### ISSUE TITLE
decade view broken?

### ISSUE THREAD

**Issue by christopherpthomas** [tempusdominus/bootstrap-3#12]
Hi there!

Don't think I'm doing anything wrong, but I'm getting crazy decades:
![decades](https://user-images.githubusercontent.com/13522974/26889450-27358a70-4ba6-11e7-897c-6cb03356ed4c.jpg)
Is this a bug?

The only non-standard thing I'm doing is that I'm using a specific date format - format: 'DD-MMM-YYYY'

**Comment by Eonasdan** [comment]
No bug, you're just that far into the future. Is it pretty there? (joking)

**Comment by Eonasdan** [comment]
Thanks for your patience. I've been pretty sick the last several months and haven't been greatly motivated to work on this. Please check the latest push and see if that fixes it for you.

**Comment by christopherpthomas** [comment]
Yes, that's great, I can work with that! Thank you so much, you're a lifesaver!
There is still a problem with the decade display, it's showing three hoverable spaces without text at the end of the list (image doesn't show mouse pointer). Clicking on them doesn't do anything, so this isn't in any urgent.
Hope you feel better soon!
![decades2](https://user-images.githubusercontent.com/13522974/27473378-ebd80388-57f6-11e7-9d6e-d39beedc1161.jpg)

**Comment by Eonasdan** [comment]
@christopherpthomas check out last commit and see what you think. This should also fix the decade view being generally ugly :)
