### ISSUE TITLE
How to change cells color based on Moment array

### ISSUE THREAD

**Issue by orney21d** [tempusdominus/bootstrap-3#14]
I can have three kind of colors defined by moment arrays of dates. How can i isue this??.

**Comment by Eonasdan** [comment]
This is a "how to" question and not an issue with the picker so please ask this question on StackOverflow.

I'll give you a head start: 
![image](https://user-images.githubusercontent.com/1006516/27645814-144c8346-5bf5-11e7-95b8-5f744e104bbf.png)

Each date has a data-day attribute and you could easily add a style to by looping over your array.
