### ISSUE TITLE
locale "th" is not loaded from moment locales

### ISSUE THREAD

**Issue by alansylim55** [tempusdominus/bootstrap-3#15]
How to load other locale file into moment.js
I am using angular2-cli for development.

Can this datepicker support year in Buddhism year ?

**Comment by Eonasdan** [comment]
You can get the locales from moment or create your own. No this picker will not support other calendar types, but you can make your own fork if you want and change whatever is needed.

**Comment by alansylim55** [comment]
appreciate if you can help to provide help..

**Comment by Eonasdan** [comment]
you can ask your question on StackOverflow. The issue tracker here is to report bugs.
