### ISSUE TITLE
Bootstrap datetimepicker is not working for culture zh-HK (Chinese-Hongkong)

### ISSUE THREAD

**Issue by KushalMaz** [tempusdominus/bootstrap-3#17]
I am working in a multilingual application and Bootstrap DateTime Picker (version : 4.17.37) is being used there. When I am using culturecode : (zh-HK), it is throwing an error called "locale is not loaded from moment locales" and the datetime picker is not working.
It would be helpful if anyone could suggest me any workaround.
Note: When I used culturecode : (zh-CN), it worked properly but I need to implement in (zh-HK).

Thanks
Kushal

**Comment by Eonasdan** [comment]
you should verify that zh-HK is a locale supported by moment. If it is, please create a jsfiddle or codepen of the issue

**Comment by William-H-M** [comment]
Hi, @Eonasdan you can close (and maybe lock this), as been solved at the bootstrap-datetimepicker git
see [#2149 ](https://github.com/Eonasdan/bootstrap-datetimepicker/issues/2149)

The thing was that moment for the zh-HK locale needs the moment-with-locales.js so it's not an error.

Thanks, and have a nice day.
