### ISSUE TITLE
DateTimePicker disabledDates assign String Array

### ISSUE THREAD

**Issue by AshishTechIT** [tempusdominus/bootstrap-3#18]
Hello All,

I'm using bootstrap datetimepicker with my ASP.net MVC5 application.
I'm trying to fetch the dates from DB, create an Array of disabled dates and then pass that array in jquery:-

C#
public String[] disabledDates { get; set; } // This model property gets set from database.

e.g. disabledDates = ["2017-08-29","2017-11-22"];

`<script type="text/javascript"> 
$(function () { 
var disabledDatesAr = '@Model.disabledDates'; 
$('#scheduleDate').datetimepicker({ 
useCurrent: false, 
minDate: new Date(), 
format: 'DD-MM-YYYY hh:mm A', 
showTodayButton: true, 
sideBySide: true, 
showClose: true, 
showClear: true, 
toolbarPlacement: 'top', 
disabledDates: disabledDatesAr 
}); 
}); 
</script>`

But the above code doesn't work and DateTimePicker popup getting disabled.
Can anyone please guide me on how to assign this array value to disabled dates?

**Comment by Eonasdan** [comment]
please post a fiddle or codepen or demo page of the issue

**Comment by AshishTechIT** [comment]
Hello Eonasdan,

Thanks for your response. I've resolved it using the suggestion provided in following link:-
https://stackoverflow.com/questions/45502237/unable-to-assign-string-array-to-bootstrap-datetimepicker-disableddates
