### ISSUE TITLE
is there any way we can set the default date to 14 days before?

### ISSUE THREAD

**Issue by Sidharthan1988** [tempusdominus/bootstrap-3#29]
is there any way we can set the default date to 14 days before?

  $('#driverEldPrintstartdatetimepicker1').datetimepicker(
  {
      format: 'MM-DD-YYYY',
      minDate: moment(d).startOf('day'),
      maxDate: new Date(),
      useCurrent: false,

  });
tried the below code in the Java script ,still it is not doing the purpose .
  $("#driverEldstartdatetimepicker1").setDate = moment().subtract(7, 'days').format("MM-DD-YYYY");

**Comment by Eonasdan** [comment]
$('#driverEldPrintstartdatetimepicker1').datetimepicker(
{
format: 'MM-DD-YYYY',
minDate: moment(d).startOf('day'),
maxDate: new Date(),
useCurrent: false,
date: moment().subtract(-14, 'days')
});

`setDate` is not a valid function
