### ISSUE TITLE
Showing duplicated dates on daylight saving transition

### ISSUE THREAD

**Issue by anperim** [tempusdominus/bootstrap-3#32]
Hi,

Using locale: "pt-br" and format: "DD/MM/YYYY" after daylight saving 15/10/2017 have a bug (see image below). Day 16 and 16 selected together.

![image](https://user-images.githubusercontent.com/11970693/31388555-d732682a-ada4-11e7-810a-f68ed959083c.png)

**Comment by William-H-M** [comment]
Hi,
1) please change the tittle issue to something more specific like "Duplicated in October".
2) This is a really big issue that's not exactly related [totally] to this plugin but rather to how the browsers manage DST time changes.

> To be clear, this is a browser issue - not a moment issue. Similar results can be obtained by just using the Date object. Moment could detect this issue and compensate, but it currently does not.

This is related with the old repo too, https://github.com/Eonasdan/bootstrap-datetimepicker/issues/2182#issuecomment-332233731

**Comment by anperim** [comment]
Thanks. ´I'll predict in my angular directive.
