### ISSUE TITLE
Can't preserve date if older than MinDate

### ISSUE THREAD

**Issue by stesvis** [tempusdominus/bootstrap-3#35]
This is my setup:
```
$('.datetimepicker').datetimepicker({
        format: 'dddd MMM DD YYYY',
        minDate: new Date(),
});
```

Basically I want to prevent them from picking a date that is in the past (to edit/create orders).
That is fine, but the problem is that when they EDIT an order that has a due date older than Today, the date field is blanked.

In my case orders with a due date in the past are marked red (overdue), and they still need to be edited PRESERVING the due date.

I understand that if i want to change the date i should only be able to pick a date >= today, but if i don't want to change the date, the textbox should still be set to the original date.

**Comment by Eonasdan** [comment]
try https://tempusdominus.github.io/bootstrap-3/Options/#keepinvalid

**Comment by stesvis** [comment]
That's it, thank you!!
