### ISSUE TITLE
Displaying Time before Date

### ISSUE THREAD

**Issue by sbuffose** [tempusdominus/bootstrap-3#38]
Hi guys! Great work!

I was wondering if there was any script that would launch first the Time display (2nd screenshot) rather than the Date (1st screenshot). In other words, this is what happens today when clicking in the **"No Icon (input field only):"** (https://eonasdan.github.io/bootstrap-datetimepicker/#no-icon-input-field-only):

<img width="1224" alt="screen shot 2017-10-17 at 10 49 54" src="https://user-images.githubusercontent.com/18401014/31668666-336a8fee-b329-11e7-914e-ef44506c9b17.png">

and I was looking Time to be the default when clicking (display first):

<img width="1220" alt="screen shot 2017-10-17 at 10 50 01" src="https://user-images.githubusercontent.com/18401014/31668696-4aa1ba3e-b329-11e7-9fa0-48ebc27f548d.png">

Thank you in advance!
Sebastian

**Comment by sanntt** [comment]
@sbuffose You probably already solved this, but serves for future reference.

There is an option called **_viewMode_**, which accepts value _'times'_ and shows time first, like so:
```javascript
$(function () {
    $('#datetimepicker1').datetimepicker({
        viewMode: "times"
    });
});
```

**Comment by sbuffose** [comment]
@sanntt, sorry for coming back so late on your answer! I tried this time ago and the error stated was _TypeError: viewMode() parameter must be one of (days, months, years, decades) value_. I haven't find the way to solve it.

Thx in advance!
Best regards,
Sebas

<img width="390" alt="screen shot 2018-02-21 at 16 48 43" src="https://user-images.githubusercontent.com/18401014/36501929-3bd1915c-1727-11e8-98eb-1af69c414d0a.png">

**Comment by sanntt** [comment]
@sbuffose That's very odd. I just tried and you are right. Maybe something changed? I remember trying and being able to show time first. Maybe I just lost my mind!

Sorry I can't be helpful!
