### ISSUE TITLE
Destroy not working as expected

### ISSUE THREAD

**Issue by lriggle-strib** [tempusdominus/bootstrap-3#39]
## Description
We are changing to this date plugin because the one we were using before does not handle times. The interface that has been built has multiple different search types, chosen via a select box. When the user selects the date search from the dropdown, the plugin is initialized and the datetimepicker interface is displayed and works as expected. However if the user clicked on date by accident, and subsequently selects something else, the plugin interface still comes up whenever the input box is clicked, which is causing issues because the other two search types expect text input that for things like names.

## What I expect
1. When the page loads, the date search is not selected by default, so the datetime plugin is not initialized
2. When I select 'Published Date' from the dropdown, the datetime plugin is initialized and allows me to choose a date if I want.
3. If I switch back to a different search type, the plugin is destroyed on the page so that non-date related input can be entered.

## What I'm seeing
1. When the page loads, the date search is not selected by default, so the datetime plugin is not initialized
2. When I select 'Published Date' from the dropdown, the datetime plugin is initialized and allows me to choose a date if I want.
3. If I switch back to a different search type, the plugin still exists and still displays when I click on the input field.

## Code
https://jsfiddle.net/852d93yo/2/

**Comment by William-H-M** [comment]
Hi, two things:
1) This issue shouldn't be posted here as this is not the library that you're referring in the code, for that should be placed on https://github.com/Eonasdan/bootstrap-datetimepicker, for now this is our  beautiful  and buggy new code :)

2) Yeah this and issue when using  ` allowInputToggle: true,` for now the "most effective" workaround without touching any code is use the following after destroy:

` $('.search .input-group.date :input').unbind('blur').unbind('focus');`

This will remove the events of datetimepicker for the input.

The other is on the code, but I do not recommend that until there's a review for that.
@Eonasdan should we review this code for merge on both repos?
Taken from: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/2121

```
detachDatePickerElementEvents = function () {
    input.off({
        'change': change,
        'blur': blur,
        'keydown': keydown,
        'keyup': keyup,
        'focus': options.allowInputToggle ? hide : ''
    });

    if (element.is('input')) {
        input.off({
            'focus': show
        });
    } else if (component) {
        component.off('click', toggle);
        component.off('mousedown', false);
    }
}
```
to

```
detachDatePickerElementEvents = function () {
    input.off({
        'change': change,
        'blur': options.debug ? '' : hide,
        'keydown': keydown,
        'keyup': keyup,
        'focus': options.allowInputToggle ? show : ''
    });

    if (element.is('input')) {
        input.off({
            'focus': show
        });
    } else if (component) {
        component.off('click', toggle);
        component.off('mousedown', false);
    }
}

```

**Comment by lriggle-strib** [comment]
@William-H-M Whoops, sorry about that. I figured posting here was ok because this is where I found the forkable fiddle. If I run into any other issues I'll post them in the other repo.

Also, your work-around works great! Thanks for the help!
