### ISSUE TITLE
Input lose focus after date selection. Jquery enter evens not work(like form submiting)

### ISSUE THREAD

**Issue by xVismutx** [tempusdominus/bootstrap-3#42]
version : 4.17.47

So need some setting - lose focus or not.
And ability to perform standart enter action.

For now even if remove blur() from hide() function -> enter not work for input and form not submit

**Comment by William-H-M** [comment]
You're reporting this on the wrong picker this is NOT http://eonasdan.github.io/bootstrap-datetimepicker/
