### ISSUE TITLE
time view displayed wrong

### ISSUE THREAD

**Issue by claudegel** [tempusdominus/bootstrap-3#44]
Hi when I'm picking a date DTP switch to time view but instead of a square table format all hour are displayed on an horizontal line and each hour are sticked side by side. Formating of time view is not working. What can I do or what's wrong
![date view](https://user-images.githubusercontent.com/4268938/31975719-2dab95e8-b901-11e7-9b0c-d71c713b9e32.png)
![minute view](https://user-images.githubusercontent.com/4268938/31975720-2dc5c968-b901-11e7-88bf-dfe63a9ca6ae.png)
![time view](https://user-images.githubusercontent.com/4268938/31975721-2dd70926-b901-11e7-96d6-57ccba306781.png)

**Comment by Eonasdan** [comment]
you're clearly missing the style sheets
