### ISSUE TITLE
YYYY-MM format Version 4.17.45

### ISSUE THREAD

**Issue by GearTheWorld** [tempusdominus/bootstrap-3#48]
Hi,

I'm using the format YYYY-MM and the first time I click the icon and the calendar shows it's working fine I select the month and the calendar disappear and I see 2017-10  Now if I click again the icon I'm in days of this month.  Is there something I have to do to make sure it always open in YYYY-MM and never go to days ?

Sorry I don't know if this is an issue but since I don't know where to ask the question.  I write it here.  Let me know if I'm at the right place!

**Comment by William-H-M** [comment]
Hi, sorry for late response 

Two things: 
1)  > Let me know if I'm at the right place!

Nop. you're not the issue should had been placed on https://github.com/Eonasdan/bootstrap-datetimepicker

2) The issue was an old bug on the version you're using I strongly suggest you to update to latest version

As this all you can clise thi. Have a nice date :)

**Comment by GearTheWorld** [comment]
1. Thank you
2. If it's a old bug it's still a bug as I have it with the latest version.  Now I'm going to the right place.

Thank you

**Comment by GearTheWorld** [comment]
Strange.  The link you gave me says it's not the right place and give the link to here.  See this screenshot :

![image](https://user-images.githubusercontent.com/8614008/32399453-6b3b4d9a-c0cc-11e7-9102-4d21600d755a.png)

**Comment by William-H-M** [comment]
Hi latest version is 4.17.47 not .45

> The link you gave me says it's not the right place and give the link to here

Nop it only say is no longer monitored by Eonasdan and no future work or option will be done (like multiple dates, thing that the first don't have but this does.)

Here a working fiddle of latest version, when confirmed pleas close.

Have a nice night :)
