### ISSUE TITLE
Is basic setup no longer supported?

### ISSUE THREAD

**Issue by CrestApps** [tempusdominus/bootstrap-3#52]
With the old version of the datetime picker https://github.com/Eonasdan/bootstrap-datetimepicker/issues/820 I use to be able to create an instance of the datetime picker using a css class name. Somethig like this

```
<div class="container">
      <div class="form-group">
          <input type="text" class="form-control datetime-picker" />
      </div>
</div>
```

```
$(function() {
   $('.datetime-picker').datetimepicker();
 });
```
Here are more example of previous usage that does not look like it is supported any longer.

https://jsfiddle.net/agbkdzhv/42/

Any chance the basic usage is added back in this version?

**Comment by Eonasdan** [comment]
You mean like https://tempusdominus.github.io/bootstrap-3/#minimum-setup ?

**Comment by CrestApps** [comment]
@Eonasdan Thank you for your response. The minimum setup seems to requests lots of HTML markup. Like so

```
<div class="form-group">
     <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
     <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker1"/>
         <span class="input-group-addon" data-target="#datetimepicker1" data-toggle="datetimepicker">
              <span class="glyphicon glyphicon-calendar"></span>
          </span>
     </div>
</div>
```

Any way to get by with the following HTML markup instead? I am trying to avoid having to change lots of my already existing HTML code to migrate to version 5.

```
      <div class="form-group">
          <input type="text" class="form-control datetime-picker" />
      </div>
```

**Comment by Eonasdan** [comment]
No there's not, this is the way forward. That's why this is a break change version
