### ISSUE TITLE
TimeZone option does not exist

### ISSUE THREAD

**Issue by kyranb** [tempusdominus/bootstrap-3#6]
See here: http://jsfiddle.net/pg0ks8dt/

``` 
$('#datetimepicker1').datetimepicker({
                            timeZone: 'UTC',
                        });
```

same for:

```
$('#datetimepicker').datetimepicker('timeZone');

```

Is this intentional/the docs need updating or its just not been added yet?

**Comment by Eonasdan** [comment]
the linked fiddle does not use Tempus Dominus. It references the old picker and not even the most recent version
