### ISSUE TITLE
Cannot read property 'position' of undefined

### ISSUE THREAD

**Issue by vmitchell85** [tempusdominus/bootstrap-3#7]
I'm getting a ton of "Cannot read property 'position' of undefined" errors when the screen is resized.

My code in use (in case it's helpful):
```js
$('#start_date').datetimepicker({
    inline: true,
    sideBySide: true,
    useCurrent: true
}).on('change.datetimepicker', function(event){
    globalDateVariable = event.date.format("YYYY-MM-DD HH:mm:00");
});
```

**Comment by Eonasdan** [comment]
can you provide a fork of this fiddle: https://jsfiddle.net/Eonasdan/3cqL9t3x/

**Comment by vmitchell85** [comment]
No fork needed... it does the same on that fiddle...

Note: You do need to open the picker and resize while it's open for it to show the errors.

![image](https://user-images.githubusercontent.com/1248035/27555109-b8e19eaa-5a7e-11e7-99fb-8c9465ce43a4.png)

The screenshot isn't in incognito, but I tested it in incognito and it also showed the error.

**Comment by Eonasdan** [comment]
ah yes I see it.
