### ISSUE TITLE
Support for Bootstrap 4 ?

### ISSUE THREAD

**Issue by seltix5** [tempusdominus/bootstrap-3#9]
hi!
is there any quick fix for bootstrap 4 ?

https://codepen.io/seltix/pen/JNaVKx

thanks :D

**Comment by Eonasdan** [comment]
ok but just for you https://github.com/tempusdominus/bootstrap-4

**Comment by seltix5** [comment]
thanks,
sorry dint find it :s
you should put this link on the bootstrap 3 version README.md =)

**Comment by Eonasdan** [comment]
np! just having a little fun with you

**Comment by seltix5** [comment]
np ^^
i updated the links to the bootstrap 4 version on build folder but the result is the same :/

**Comment by Eonasdan** [comment]
I fixed this issue in this repo. You're welcome to open an other ticket in the BS4 repo.
