### ISSUE TITLE
Full localization support

### ISSUE THREAD

**Issue by chilio** [tempusdominus/bootstrap-3#98]
Great package but, although this is localized via moment.js there are some things that are not localized and  I mean hovers here like `next Month`.
Do you plan extending this to full localization support?

**Comment by Eonasdan** [comment]
you mean like this: https://tempusdominus.github.io/bootstrap-3/Options/#tooltips

**Comment by chilio** [comment]
Hmm yeah, 
Yes I could add them by the hand, as in your link...
But wouldn't  be it more usable to add  translations to the package?
